### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by sdjyliqi** [guojun1992/2017GopherChina#1]
你好 大神

https://github.com/gorilla/websocket/issues/362

看到你的帖子，这个问题 最后怎么解决的呀。。。我也出现类似问题。 可以邮箱联系一下吗？？  sdjyliqi@163.com

**Comment by guojun1992** [comment]
hello，这个问题是很正常的，读不出数据，返回error，只要和目标server断掉链接，就释放链接，然后重新链接就可以了
